### ISSUE TITLE
Can't see all conferences

### ISSUE THREAD

**Issue by gmembre-zenika** [bpetetot/conference-hall-beta#446] opened 2019-01-15 15:39 UTC
I have open the link from julien to submit the "TZ 2019". My submission is OK, now I want to see all the conference available and I can't get out of "TZ 2019". Where do I click to see all the available conf ?
I have open conference hall in private browsing and I can see them.

![image](https://user-images.githubusercontent.com/7294764/51191044-d9122a80-18e3-11e9-8b95-af233d7c563c.png)

**Comment by vincent-vimard** [comment] 2019-01-15 15:42
I have the same problem !

**Comment by bpetetot** [comment] 2019-01-15 16:08
Yes for now I don't have a page with all events listed, it's coming soon. Anyway you can see all public events by clicking submit on a talk, then select the event, and you will have it on the left side.

**Comment by corinnekrych** [comment] 2019-01-22 14:02
similar, possible duplicate of https://github.com/bpetetot/conference-hall/issues/439

**Comment by Swiip** [comment] 2019-02-21 15:49
+1 for a page with all events. There is now several confs which uses Conference Hall which is cool 💪 but as a speaker, I can't switch from a conference to another without an external link.

**Comment by bpetetot** [comment] 2019-03-13 22:10
Indeed this is a duplicate of #439 with UX issue to find events and how to see all speaker submissions

**Closed as completed by bpetetot** 2019-03-13 22:10 UTC
