### ISSUE TITLE
[organizer] Sort by "newest" doesn't work

### ISSUE THREAD

**Issue by jlandure** [bpetetot/conference-hall-beta#451] opened 2019-01-28 20:58 UTC
The "newest" sort seems to be broken. I saw new talks but the first ones are always the same in the "Proposals"...

**Comment by corinnekrych** [comment] 2019-01-30 08:35
possible duplicate of https://github.com/bpetetot/conference-hall/issues/416

**Comment by bpetetot** [comment] 2019-03-13 22:41
Thx for the feedback @jlandure, Indeed closing it because duplicate of #416
PR in progress ;)

**Closed as completed by bpetetot** 2019-03-13 22:41 UTC
Labels: :bug: bug
